
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/11saitama_dev.ipynb

import bs4
import re
import csv
import datetime
import requests

URL = 'https://www.pref.saitama.lg.jp/a0701/covid19/jokyo.html'

def get_src():
    response = requests.get(URL)
    response.encoding = response.apparent_encoding
    return bs4.BeautifulSoup(response.text, 'html.parser')

def _get_table(src):
    tbody = src.find_all("tbody")[2]
    return tbody.find_all('tr')

def _header(table):
    return [th.text.strip() for th in table[0].find_all('th')]

def _parse_no(td):
    if td.a:
        return td.a.get_text(), td.a.get('href')
    else:
        return td.text.strip(), 'NA'

def _trim(td):
    return re.sub('\r\n\s+', '\u3002', re.sub('[\xa0\u3000]', '', td.text))

def _parse(table, colum_num):
    patients = []
    for tr in table[1:]:
        tds = tr.find_all('td')
        no, link = _parse_no(tds[0])
        td = [no]
        for t in tds[1:]:
            td.append(_trim(t))
        for i in range(colum_num-len(td)):
            td.append('')
        td.append(link)
        patients.append(td)
    return patients

def get_patients():
    src = get_src()
    table = _get_table(src)
    col = _header(table)
    return _parse(table, len(col))

def create_fname(base):
    now = datetime.datetime.now()
    return base + '_' + now.strftime('%Y%m%dT%H%M') + ".csv"

def write_csv(patients, fname):
    with open(fname, 'w') as f:
        writer = csv.writer(f)
        writer.writerows(patients)

def main():
    patients = get_patients()
    write_csv(patients, create_fname("data/11saitama"))

if __name__ == '__main__':
    main()